github:
  description: "Apache Archiva Redback Repository"
  homepage: https://archiva.apache.org
  labels:
    - apache
    - java
    - archiva
    - maven-repository
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: false
    # Enable projects for project management boards
    projects: true
notifications:
  commits:      commits@archiva.apache.org
  issues:       dev@archiva.apache.org
  pullrequests: dev@archiva.apache.org
  jira_options: link label comment

