language: java
dist: bionic
jdk:
  - openjdk8

script: "mvn clean install"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - olamy@apache.org
